[2025-08-15T19:57:03.040+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_quotes.load_quotes_task manual__2025-08-15T19:56:53.858525+00:00 [queued]>
[2025-08-15T19:57:03.051+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_quotes.load_quotes_task manual__2025-08-15T19:56:53.858525+00:00 [queued]>
[2025-08-15T19:57:03.051+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-08-15T19:57:03.063+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_quotes_task> on 2025-08-15 19:56:53.858525+00:00
[2025-08-15T19:57:03.071+0000] {standard_task_runner.py:60} INFO - Started process 930 to run task
[2025-08-15T19:57:03.073+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_quotes', 'load_quotes_task', 'manual__2025-08-15T19:56:53.858525+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/etl_quotes.py', '--cfg-path', '/tmp/tmpfngk32bx']
[2025-08-15T19:57:03.075+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask load_quotes_task
[2025-08-15T19:57:03.091+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-15T19:57:03.128+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_quotes.load_quotes_task manual__2025-08-15T19:56:53.858525+00:00 [running]> on host ce06bc1fd883
[2025-08-15T19:57:03.219+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_quotes' AIRFLOW_CTX_TASK_ID='load_quotes_task' AIRFLOW_CTX_EXECUTION_DATE='2025-08-15T19:56:53.858525+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-15T19:56:53.858525+00:00'
[2025-08-15T19:57:03.243+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedColumn: column "data_transformacao" of relation "quotes" does not exist
LINE 1: INSERT INTO quotes (frase, autor, data_transformacao) VALUES...
                                          ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/load_quotes.py", line 22, in carregar_frases
    df.to_sql("quotes", engine, if_exists="append", index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2878, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 769, in to_sql
    return pandas_sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1920, in to_sql
    total_inserted = sql_engine.insert_records(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1470, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1461, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1023, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 929, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "data_transformacao" of relation "quotes" does not exist
LINE 1: INSERT INTO quotes (frase, autor, data_transformacao) VALUES...
                                          ^

[SQL: INSERT INTO quotes (frase, autor, data_transformacao) VALUES (%(frase)s, %(autor)s, %(data_transformacao)s)]
[parameters: ({'frase': 'The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.', 'autor': 'Albert Einstein', 'data_transformacao': '2025-08-15 19:57:01'}, {'frase': 'It is our choices, Harry, that show what we truly are, far more than our abilities.', 'autor': 'J.K. Rowling', 'data_transformacao': '2025-08-15 19:57:01'}, {'frase': 'There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.', 'autor': 'Albert Einstein', 'data_transformacao': '2025-08-15 19:57:01'}, {'frase': 'The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.', 'autor': 'Jane Austen', 'data_transformacao': '2025-08-15 19:57:01'}, {'frase': "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.", 'autor': 'Marilyn Monroe', 'data_transformacao': '2025-08-15 19:57:01'}, {'frase': 'Try not to become a man of success. Rather become a man of value.', 'autor': 'Albert Einstein', 'data_transformacao': '2025-08-15 19:57:01'}, {'frase': 'It is better to be hated for what you are than to be loved for what you are not.', 'autor': 'Andr√© Gide', 'data_transformacao': '2025-08-15 19:57:01'}, {'frase': "I have not failed. I've just found 10,000 ways that won't work.", 'autor': 'Thomas A. Edison', 'data_transformacao': '2025-08-15 19:57:01'}  ... displaying 10 of 100 total bound parameter sets ...  {'frase': "A person's a person, no matter how small.", 'autor': 'Dr. Seuss', 'data_transformacao': '2025-08-15 19:57:01'}, {'frase': '... a mind needs books as a sword needs a whetstone, if it is to keep its edge.', 'autor': 'George R.R. Martin', 'data_transformacao': '2025-08-15 19:57:01'})]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-08-15T19:57:03.264+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=etl_quotes, task_id=load_quotes_task, execution_date=20250815T195653, start_date=20250815T195703, end_date=20250815T195703
[2025-08-15T19:57:03.274+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 14 for task load_quotes_task ((psycopg2.errors.UndefinedColumn) column "data_transformacao" of relation "quotes" does not exist
LINE 1: INSERT INTO quotes (frase, autor, data_transformacao) VALUES...
                                          ^

[SQL: INSERT INTO quotes (frase, autor, data_transformacao) VALUES (%(frase)s, %(autor)s, %(data_transformacao)s)]
[parameters: ({'frase': 'The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.', 'autor': 'Albert Einstein', 'data_transformacao': '2025-08-15 19:57:01'}, {'frase': 'It is our choices, Harry, that show what we truly are, far more than our abilities.', 'autor': 'J.K. Rowling', 'data_transformacao': '2025-08-15 19:57:01'}, {'frase': 'There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.', 'autor': 'Albert Einstein', 'data_transformacao': '2025-08-15 19:57:01'}, {'frase': 'The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.', 'autor': 'Jane Austen', 'data_transformacao': '2025-08-15 19:57:01'}, {'frase': "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.", 'autor': 'Marilyn Monroe', 'data_transformacao': '2025-08-15 19:57:01'}, {'frase': 'Try not to become a man of success. Rather become a man of value.', 'autor': 'Albert Einstein', 'data_transformacao': '2025-08-15 19:57:01'}, {'frase': 'It is better to be hated for what you are than to be loved for what you are not.', 'autor': 'Andr√© Gide', 'data_transformacao': '2025-08-15 19:57:01'}, {'frase': "I have not failed. I've just found 10,000 ways that won't work.", 'autor': 'Thomas A. Edison', 'data_transformacao': '2025-08-15 19:57:01'}  ... displaying 10 of 100 total bound parameter sets ...  {'frase': "A person's a person, no matter how small.", 'autor': 'Dr. Seuss', 'data_transformacao': '2025-08-15 19:57:01'}, {'frase': '... a mind needs books as a sword needs a whetstone, if it is to keep its edge.', 'autor': 'George R.R. Martin', 'data_transformacao': '2025-08-15 19:57:01'})]
(Background on this error at: https://sqlalche.me/e/14/f405); 930)
[2025-08-15T19:57:03.285+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-15T19:57:03.304+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
